### PR TITLE
Update to 1.9

### PR DESCRIPTION
**Pull request by Xephi**
Make AlmostFlatLands compile for 1.9

### CODE REVIEW

**Comment by betterphp** [comment]
Awesome thanks. I'm going to update all my plugins over the next few weeks so you may have just saved me one to do :)

Will this actually compile without the craftbukkit dependency and the references to net.minecraft.server still in there?

Also could you leave the dev.bukkit.org upload tag in pom.xml? I don't plan on ever using DBO again but there's no reason to remove it really.

**Comment by Xephi** [comment]
Spigot dependency already include the craftbukkit api, by the way, i have reduce from spigot to cb ^^
I've re-add the dbo too :p

**Comment by betterphp** [comment]
Ah okay, I'm pretty out of date with this stuff, happy with the code changes anyway so I'll merge and see what happens :P

**Comment by betterphp** [comment]
Hmm build failed downloading Craftbukkit https://ci.jacekk.co.uk/job/AlmostFlatLands/30/console

I guess this is that whole legal thing of not being able to distribute it.

Maybe if I get Jenkins to build CraftBukkit using BuildTools as a private job so it can get the dependency from there?

I'm sure there's a standard way to deal with this. I'll Google.

**Comment by betterphp** [comment]
Got Jenkins to build Craftbukkit and Spigot - works now https://ci.jacekk.co.uk/job/AlmostFlatLands/31/ \o/

**Comment by Xephi** [comment]
Nice :D

**Comment by betterphp** [comment]
Thanks for contributing :)

**Pull request merged**
